import Head from "next/head";
import { Text, Center, Container, Button, Flex } from "@mantine/core";
import { DetectionModel } from "@/model/detection_model";
import { useEffect, useState } from "react";
import DetectionTable from "@/component/table";
import { LoadingScreen } from "../component/loading_screen";

export default function Home() {
  const [isFetching, setIsFetching] = useState(true);
  const [data, setData] = useState<DetectionModel[] | null>(null);

  useEffect(() => {
    fetch("/api/get_data")
      .then((response) => response.json())
      .then((resp) => setData(resp.data))
      .catch((error) => setData(null))
      .finally(() =>{
        setTimeout(() => {
          setIsFetching(false);
      }, 1000);
      });
  }, []);
  if (isFetching) return <LoadingScreen />;
  return (
    <>
      <Head>
        <title>Smart Detection</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="pageSetting">
        <Container>
          <Center mah={1000} maw={1000} mx="auto">
            {data === null || data.length === 0 ? (
              <Flex
                mih={50}
                gap="md"
                justify="center"
                align="center"
                direction="column"
              >
                <Text>No data availables. (or database connection error)</Text>
                <Button
                  variant="gradient"
                  gradient={{ from: "orange", to: "red" }}
                  radius="lg"
                  size="lg"
                  onClick={() => window.location.reload()}
                >
                  Refresh
                </Button>
              </Flex>
            ) : (
              <Flex
                mih={50}
                gap="md"
                justify="center"
                align="center"
                direction="column"
              >
                <DetectionTable records={data} />
                <Button
                  variant="gradient"
                  gradient={{ from: "orange", to: "red" }}
                  radius="lg"
                  size="lg"
                  onClick={() => window.location.reload()}
                >
                  Refresh
                </Button>
              </Flex>
            )}
          </Center>
        </Container>
      </main>
    </>
  );
}
